Traceback (most recent call last):
  File "/Users/ysbach/miniforge3/lib/python3.10/site-packages/nbclient/client.py", line 730, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/Users/ysbach/miniforge3/lib/python3.10/site-packages/nbclient/util.py", line 96, in ensure_async
    result = await obj
  File "/Users/ysbach/miniforge3/lib/python3.10/site-packages/jupyter_client/channels.py", line 315, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ysbach/miniforge3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/ysbach/miniforge3/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/ysbach/miniforge3/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/ysbach/miniforge3/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/ysbach/miniforge3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/ysbach/miniforge3/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/ysbach/miniforge3/lib/python3.10/site-packages/nbclient/client.py", line 949, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/Users/ysbach/miniforge3/lib/python3.10/site-packages/nbclient/client.py", line 754, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/Users/ysbach/miniforge3/lib/python3.10/site-packages/nbclient/client.py", line 801, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['# =====', '# If you want to use MAST, only DR2 is available as of 2023-04-26. ', '# You can uncomment q_gaia line.', '# Gaia DR2 needs `version=2`', '# q_gaia = Catalogs.query_region(center_coo, radius=fov_radius, catalog="Gaia", version=2) ']
...
['q_ps["gMeanPSFMag"].name = "g"', 'q_ps["rMeanPSFMag"].name = "r"', '', 'print("Number of results:",len(q_gaia))', 'print("Number of results:",len(q_ps))']
-------------------

